# Generated by Django 2.2.2 on 2019-06-29 20:07

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='blocks',
            field=django_mysql.models.ListCharField(models.CharField(max_length=3), blank=True, max_length=1500, size=50),
        ),
        migrations.AddField(
            model_name='customuser',
            name='links',
            field=django_mysql.models.ListCharField(models.CharField(max_length=3), blank=True, max_length=4500, size=150),
        ),
    ]
