# Generated by Django 2.2.2 on 2019-06-30 18:48

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20190629_2007'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='block_names',
            field=django_mysql.models.ListCharField(models.CharField(max_length=3), blank=True, max_length=15000, size=50),
        ),
    ]
