# Generated by Django 2.2.2 on 2019-06-30 18:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_block_names'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='block_names',
        ),
    ]
