# Generated by Django 2.2.4 on 2020-03-03 04:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_customuser_language_preference'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='language_preference',
            field=models.CharField(blank=True, default='en', max_length=10, verbose_name='lang_pref'),
        ),
    ]
