# Generated by Django 3.0.2 on 2020-03-20 14:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20200303_0426'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='blocks',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='links',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='language_preference',
            field=models.CharField(default='en', max_length=10, verbose_name='lang_pref'),
        ),
    ]
