# Generated by Django 3.0.2 on 2020-03-28 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_auto_20200328_1708'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Admin',
            new_name='Researcher',
        ),
        migrations.RenameField(
            model_name='participant',
            old_name='admin',
            new_name='researcher',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_participant',
            field=models.BooleanField(default=False),
        ),
    ]
