# Generated by Django 3.0.2 on 2020-03-29 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_auto_20200329_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='project',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Project'),
        ),
        migrations.AlterField(
            model_name='participant',
            name='researcher',
            field=models.ForeignKey(blank=True, default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='users.Researcher'),
        ),
    ]
