# Generated by Django 3.0.2 on 2020-04-03 21:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0022_auto_20200403_2132'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='part_name',
            new_name='name_participants',
        ),
    ]
