# Generated by Django 3.0.2 on 2020-04-03 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0023_auto_20200403_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name_participants',
            field=models.CharField(default='', error_messages={'required': 'Please choose a star rating'}, max_length=10, unique=True),
        ),
    ]
