# Generated by Django 3.0.2 on 2020-04-18 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_auto_20200414_0115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='name_participants',
            field=models.CharField(blank=True, default='', max_length=10, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='project',
            name='num_part',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
    ]
