# Generated by Django 3.0.2 on 2020-04-18 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0032_auto_20200418_2211'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cam_image',
        ),
        migrations.AddField(
            model_name='cam',
            name='cam_image',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
