# Generated by Django 3.0.2 on 2020-04-18 22:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0033_auto_20200418_2215'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='cam_image',
            field=models.ImageField(default='', upload_to=''),
        ),
    ]
