# Generated by Django 3.0.2 on 2020-04-18 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0034_auto_20200418_2216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='cam_image',
            field=models.FileField(default='', upload_to=''),
        ),
    ]
