# Generated by Django 2.2.6 on 2020-06-08 23:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0036_project_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='cam',
            name='creation_date',
            field=models.DateField(default=datetime.date.today, verbose_name='Date'),
        ),
    ]
