# Generated by Django 3.0.2 on 2020-06-10 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0043_auto_20200610_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='creation_date',
            field=models.CharField(default='2020-06-10 20:29:08.622327', max_length=100, verbose_name='Date'),
        ),
    ]
