# Generated by Django 2.2.6 on 2020-08-23 16:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0045_auto_20200610_2032'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='random_user',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='cam',
            name='creation_date',
            field=models.CharField(default=datetime.datetime(2020, 8, 23, 16, 35, 13, 365861), max_length=100, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Initial_CAM',
            field=models.FileField(default='', upload_to='../media/InitialCAMs/'),
        ),
    ]
