# Generated by Django 2.2.6 on 2020-08-23 16:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0046_auto_20200823_1635'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='creation_date',
            field=models.CharField(default=datetime.datetime(2020, 8, 23, 16, 38, 51, 40934), max_length=100, verbose_name='Date'),
        ),
    ]
