# Generated by Django 3.2.3 on 2021-06-15 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0047_auto_20200823_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='creation_date',
            field=models.CharField(default=datetime.datetime(2021, 6, 15, 19, 27, 43, 381886), max_length=100, verbose_name='Date'),
        ),
    ]
