# Generated by Django 3.2 on 2021-06-26 19:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0048_alter_cam_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='creation_date',
            field=models.CharField(default=datetime.datetime(2021, 6, 26, 19, 9, 27, 132078), max_length=100, verbose_name='Date'),
        ),
    ]
