# Generated by Django 3.2.3 on 2021-06-15 20:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0049_alter_cam_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='creation_date',
            field=models.CharField(default=datetime.datetime(2021, 6, 15, 20, 21, 26, 297315), max_length=100, verbose_name='Date'),
        ),
    ]
