# Generated by Django 3.2.5 on 2021-07-16 21:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0050_alter_cam_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='creation_date',
            field=models.CharField(default=datetime.datetime(2021, 7, 16, 21, 9, 55, 937734), max_length=100, verbose_name='Date'),
        ),
    ]
