# Generated by Django 3.2.5 on 2021-07-17 21:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0051_alter_cam_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='creation_date',
            field=models.CharField(default=datetime.datetime(2021, 7, 17, 21, 26, 23, 357165), max_length=100, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='avatar',
            field=models.ImageField(blank=True, default='', null=True, upload_to='avatar/'),
        ),
        migrations.AlterField(
            model_name='project',
            name='Initial_CAM',
            field=models.FileField(default='', upload_to='InitialCAMs/'),
        ),
    ]
