# Generated by Django 3.2.5 on 2021-07-21 14:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0052_auto_20210717_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='creation_date',
            field=models.CharField(default=datetime.datetime(2021, 7, 21, 14, 15, 24, 407966), max_length=100, verbose_name='Date'),
        ),
    ]
