# Generated by Django 3.2.3 on 2021-07-28 17:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0053_alter_cam_creation_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cam',
            name='description',
            field=models.CharField(blank=True, default=' ', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='cam',
            name='creation_date',
            field=models.CharField(default=datetime.datetime(2021, 7, 28, 17, 45, 3, 816951), max_length=100, verbose_name='Date'),
        ),
    ]
