# Generated by Django 3.2 on 2021-10-19 00:09

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0054_auto_20210728_1745'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='creation_date',
            field=models.CharField(default=datetime.datetime(2021, 10, 19, 0, 9, 38, 328494), max_length=100, verbose_name='Date'),
        ),
    ]
