# Generated by Django 3.2.3 on 2021-10-23 18:47

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0058_alter_cam_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='creation_date',
            field=models.CharField(default=datetime.datetime(2021, 10, 23, 18, 47, 36, 399512), max_length=100, verbose_name='Date'),
        ),
        migrations.CreateModel(
            name='logCamActions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('actionId', models.IntegerField()),
                ('actionType', models.IntegerField()),
                ('objType', models.IntegerField()),
                ('objDetails', models.CharField(max_length=50)),
                ('camId', models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.cam')),
            ],
        ),
    ]
