# Generated by Django 3.2.5 on 2021-10-27 20:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0059_alter_cam_creation_date'),
        ('users', '0059_auto_20211023_1847'),
    ]

    operations = [
    ]
