# Generated by Django 3.2.5 on 2021-10-27 23:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0061_alter_cam_creation_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cam',
            name='creation_date',
            field=models.CharField(default=datetime.datetime(2021, 10, 27, 23, 49, 56, 941519), max_length=100, verbose_name='Date'),
        ),
        migrations.AlterField(
            model_name='logcamactions',
            name='objDetails',
            field=models.CharField(max_length=250),
        ),
    ]
