# Generated by Django 4.2.25 on 2025-10-26 00:51

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0062_auto_20211027_2349"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cam",
            name="creation_date",
            field=models.CharField(
                default=datetime.datetime.now, max_length=100, verbose_name="Date"
            ),
        ),
        migrations.AlterField(
            model_name="contact",
            name="email",
            field=models.EmailField(max_length=256),
        ),
        migrations.AlterField(
            model_name="logcamactions",
            name="objDetails",
            field=models.CharField(max_length=500),
        ),
    ]
