# Generated by Django 2.2.1 on 2019-06-24 00:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='border_color',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='block',
            name='border_style',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
