# Generated by Django 2.2.1 on 2019-06-24 01:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0002_auto_20190624_0019'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='border_color',
            field=models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green')], max_length=100),
        ),
        migrations.AlterField(
            model_name='block',
            name='border_style',
            field=models.CharField(choices=[('solid', 'solid'), ('dashed', 'dashed'), ('dotted', 'dotted')], max_length=100),
        ),
    ]
