# Generated by Django 2.2.2 on 2019-06-24 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0003_auto_20190624_0121'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='shape',
            field=models.CharField(choices=[('rectangle', 'rectangle'), ('rounded', 'rounded'), ('hexagon', 'hexagon')], default='', max_length=100),
            preserve_default=False,
        ),
    ]
