# Generated by Django 2.2.2 on 2019-06-24 22:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0004_block_shape'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='creator',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='block',
            name='shape',
            field=models.CharField(choices=[('rectangle', 'rectangle'), ('circle', 'rounded-circle'), ('hexagon', 'hexagon')], max_length=100),
        ),
    ]
