# Generated by Django 2.2.2 on 2019-06-29 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0005_auto_20190624_2231'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='x_pos',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='block',
            name='y_pos',
            field=models.FloatField(default=0.0),
        ),
    ]
