# Generated by Django 2.2.2 on 2019-07-03 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0006_auto_20190629_2023'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='border_color',
        ),
        migrations.RemoveField(
            model_name='block',
            name='border_style',
        ),
        migrations.AlterField(
            model_name='block',
            name='shape',
            field=models.CharField(choices=[('neutral', 'rectangle'), ('positive', 'rounded-circle'), ('negative', 'hexagon'), ('ambivalent', 'hexagon rounded-circle')], max_length=100),
        ),
    ]
