# Generated by Django 2.2.2 on 2019-07-03 22:48

from django.db import migrations, models
import django_mysql.models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0007_auto_20190703_1704'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='links',
            field=django_mysql.models.ListCharField(models.CharField(max_length=3), blank=True, max_length=4500, size=150),
        ),
    ]
