# Generated by Django 2.2.2 on 2019-07-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0008_block_links'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='num',
            field=models.FloatField(blank=True, default=0),
        ),
    ]
