# Generated by Django 2.2.4 on 2019-08-29 12:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0009_block_num'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='shape',
            field=models.CharField(choices=[('neutral', 'rectangle'), ('positive', 'rounded-circle'), ('negative', 'hexagon'), ('positive_strong', 'rounded-circle strong'), ('negative_strong', 'hexagon strong'), ('ambivalent', 'hexagon rounded-circle')], max_length=100),
        ),
    ]
