# Generated by Django 2.2.4 on 2019-09-02 16:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0010_auto_20190829_1210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='shape',
            field=models.CharField(choices=[('neutral', 'rectangle'), ('positive', 'rounded-circle'), ('negative', 'hexagon'), ('positive strong', 'rounded-circle strong'), ('negative strong', 'hexagon strong'), ('ambivalent', 'hexagon rounded-circle')], max_length=100),
        ),
    ]
