# Generated by Django 2.2.6 on 2019-10-23 17:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0011_auto_20190902_1633'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='title',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
    ]
