# Generated by Django 2.2.6 on 2020-02-10 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0013_auto_20200119_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
