# Generated by Django 2.2.6 on 2020-02-10 06:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0014_block_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='comment',
            field=models.CharField(blank=True, default='', max_length=300, null=True),
        ),
    ]
