# Generated by Django 2.2.6 on 2020-02-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0015_auto_20200210_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='timestamp',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
