# Generated by Django 2.2.4 on 2020-02-26 05:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0016_block_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='modifiable',
            field=models.BooleanField(blank=True, default=True, null=True),
        ),
    ]
