# Generated by Django 2.2.4 on 2020-02-26 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0017_block_modifiable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='comment',
            field=models.CharField(blank=True, default=' ', max_length=300, null=True),
        ),
    ]
