# Generated by Django 3.0.2 on 2020-03-20 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('block', '0020_auto_20200229_2327'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='block',
            name='links',
        ),
        migrations.AlterField(
            model_name='block',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
