# Generated by Django 3.0.2 on 2020-03-25 01:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_auto_20200325_0127'),
        ('block', '0021_auto_20200320_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='CAM',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.CAM'),
        ),
    ]
