# Generated by Django 3.2 on 2021-06-26 19:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0023_auto_20200516_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='text_scale',
            field=models.FloatField(blank=True, default=14),
        ),
    ]
