# Generated by Django 3.2 on 2021-10-19 01:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0025_alter_block_text_scale'),
    ]

    operations = [
        migrations.AddField(
            model_name='block',
            name='resizable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
