# Generated by Django 3.2 on 2021-10-19 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0026_block_resizable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='resizable',
            field=models.BooleanField(default=False),
        ),
    ]
