# Generated by Django 3.2 on 2021-10-20 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('block', '0027_alter_block_resizable'),
    ]

    operations = [
        migrations.AlterField(
            model_name='block',
            name='resizable',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
