[phases.setup]
nixPkgs = ["python311Full"]

[phases.install]
cmds = ["pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput || echo 'No static files to collect'"]

[release]
cmd = "python manage.py migrate"

[start]
cmd = "gunicorn cognitiveAffectiveMaps.wsgi --bind 0.0.0.0:$PORT"
