[build]
builder = "nixpacks"

[deploy]
startCommand = "python manage.py migrate && gunicorn cognitiveAffectiveMaps.wsgi --bind 0.0.0.0:$PORT"
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10
