# Generated by Django 2.2.2 on 2019-06-29 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('starting_block', models.IntegerField(default=0)),
                ('ending_block', models.IntegerField(default=0)),
                ('border_style', models.CharField(choices=[('solid', 'solid'), ('dashed', 'dashed'), ('dotted', 'dotted')], max_length=100)),
                ('border_color', models.CharField(choices=[('red', 'red'), ('blue', 'blue'), ('green', 'green')], max_length=100)),
                ('creator', models.CharField(default='', max_length=100)),
            ],
        ),
    ]
