# Generated by Django 2.2.2 on 2019-06-30 18:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0003_auto_20190630_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='num',
            field=models.IntegerField(default=0),
        ),
    ]
