# Generated by Django 2.2.2 on 2019-06-30 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0004_link_num'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='name',
            field=models.IntegerField(default=0),
        ),
    ]
