# Generated by Django 2.2.2 on 2019-07-03 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0005_link_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='line_color',
        ),
        migrations.AddField(
            model_name='link',
            name='line_style',
            field=models.CharField(choices=[('solid', 'solid'), ('dashed', 'dashed')], default='solid', max_length=100),
        ),
    ]
