# Generated by Django 2.2.2 on 2019-07-16 21:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0006_auto_20190703_1623'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='end_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='end_y',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='start_x',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='link',
            name='start_y',
            field=models.FloatField(default=0),
        ),
    ]
