# Generated by Django 2.2.1 on 2019-08-27 22:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0007_auto_20190716_2140'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='name',
        ),
    ]
