# Generated by Django 2.2.6 on 2019-11-27 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0008_remove_link_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='line_type',
            field=models.CharField(default='bold', max_length=100),
        ),
    ]
