# Generated by Django 2.2.6 on 2020-02-01 00:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0009_link_line_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='arrow_type',
            field=models.CharField(choices=[('none', 'none'), ('uni', 'uni'), ('bi', 'bi')], default='none', max_length=100),
        ),
    ]
