# Generated by Django 2.2.6 on 2020-02-08 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0010_link_arrow_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='line_type',
        ),
        migrations.RemoveField(
            model_name='link',
            name='line_width',
        ),
        migrations.AlterField(
            model_name='link',
            name='line_style',
            field=models.CharField(choices=[('Solid', 'Solid'), ('Solid-Strong', 'Solid-Strong'), ('Solid-Weak', 'Solid-Weak'), ('Dashed', 'Dashed'), ('Dashed-Strong', 'Dashed-Strong'), ('Dashed-Weak', 'Dashed-Weak')], default='Solid', max_length=100),
        ),
    ]
