# Generated by Django 2.2.6 on 2020-02-10 18:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0011_auto_20200208_0357'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='timestamp',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
