# Generated by Django 3.0.2 on 2020-03-20 14:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('block', '0021_auto_20200320_1454'),
        ('link', '0012_link_timestamp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='link',
            name='end_x',
        ),
        migrations.RemoveField(
            model_name='link',
            name='end_y',
        ),
        migrations.RemoveField(
            model_name='link',
            name='start_x',
        ),
        migrations.RemoveField(
            model_name='link',
            name='start_y',
        ),
        migrations.AlterField(
            model_name='link',
            name='creator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='link',
            name='ending_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ending_block_set', to='block.Block'),
        ),
        migrations.AlterField(
            model_name='link',
            name='starting_block',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='starting_block_set', to='block.Block'),
        ),
    ]
