# Generated by Django 3.0.2 on 2020-03-28 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_auto_20200328_1925'),
        ('link', '0013_auto_20200320_1454'),
    ]

    operations = [
        migrations.AddField(
            model_name='link',
            name='CAM',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='users.CAM'),
        ),
    ]
