# Generated by Django 3.0.2 on 2020-06-10 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('link', '0014_link_cam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='link',
            name='line_style',
            field=models.CharField(choices=[('Solid', 'Solid'), ('Solid-Strong', 'Solid-Strong'), ('Solid-Weak', 'Solid-Weak'), ('Dashed', 'Dashed'), ('Dashed-Strong', 'Dashed-Strong'), ('Dashed-Weak', 'Dashed-Weak')], default='Solid-Weak', max_length=100),
        ),
    ]
