name: CI

on:
  push:
    branches: [ master, Heroku ]
  pull_request:
    branches: [ master, Heroku ]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      postgres:
        image: postgres:13
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: test_valence
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    env:
      DATABASE_URL: postgresql://postgres:postgres@localhost:5432/test_valence
      DJANGO_SETTINGS_MODULE: cognitiveAffectiveMaps.settings_local
      SECRET_KEY: test-secret-key-for-ci
      DEBUG: False

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
        cache: 'pip'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install pytest-cov coverage
        pip install -r requirements.txt

    - name: Run migrations
      run: |
        python manage.py migrate --noinput

    - name: Run tests with coverage
      run: |
        pytest --cov --cov-report=xml --cov-report=term --cov-report=html

    - name: Check coverage threshold
      run: |
        coverage report --fail-under=60

    - name: Upload coverage reports
      uses: codecov/codecov-action@v3
      if: always()
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false

    - name: Upload coverage HTML report
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: coverage-report
        path: htmlcov/
